from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors

def create_workout_pdf(filename):
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter

    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width / 2, height - 50, "2 Full Day Full Body Workout Program")

    # Draw a line under title
    c.setLineWidth(1)
    c.line(50, height - 60, width - 50, height - 60)

    # Day 1 Section
    y_position = height - 100
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y_position, "Day 1")
    
    y_position -= 30
    c.setFont("Helvetica", 12)
    exercises_day_1 = [
        "Barbell Back Squats",
        "Bench Press",
        "Lateral Raises",
        "Face Pulls",
        "Tricep Pushdowns"
    ]

    for exercise in exercises_day_1:
        c.drawString(70, y_position, f"- {exercise}")
        y_position -= 20

    # Day 2 Section
    y_position -= 20
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y_position, "Day 2")

    y_position -= 30
    c.setFont("Helvetica", 12)
    exercises_day_2 = [
        "Bulgarian Split Squats",
        "Hyperextension",
        "Seated Row",
        "Lat Pulldown",
        "Plank"
    ]

    for exercise in exercises_day_2:
        c.drawString(70, y_position, f"- {exercise}")
        y_position -= 20

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(width / 2, 50, "Generated by Plant Based Balance Assistant")

    c.save()
    print(f"PDF created: {filename}")

if __name__ == "__main__":
    create_workout_pdf("2_Day_Full_Body_Workout.pdf")
