const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs'); const vm=require('node:vm');
const source=fs.readFileSync('js/dashboard/dashboard-script-5-initialize_stripe_for_inapp_pu.js','utf8');
const helpers=source.slice(source.indexOf('function getExerciseRestSeconds('),source.indexOf('function addWorkoutSet('));
const timer=source.slice(source.indexOf('let _restTimerInterval = null;'),source.indexOf('// Retry save with exponential backoff'));
function setup(){let now=1000, tick;const elements={};const ctx={Date:{now:()=>now},Number,String,Math,Object,localStorage:{getItem:()=>null,setItem:()=>{}},document:{getElementById:id=>elements[id]||(elements[id]={style:{},textContent:''}),querySelector:()=>null},navigator:{},requestAnimationFrame:f=>f(),setInterval:f=>(tick=f,1),clearInterval:()=>{},setTimeout:()=>1,clearTimeout:()=>{}};vm.createContext(ctx);vm.runInContext(helpers+timer,ctx);return{ctx,elements,advance:n=>{now+=n;tick();}};}
test('compound, accessory, bodyweight and coach durations',()=>{const {ctx}=setup();for(const name of ['Romanian Deadlift','Dumbbell Bench Press','Kneeling Push Up','Single Arm Row'])assert.equal(ctx.getExerciseRestSeconds(name),90);for(const name of ['Standing Dumbbell Bicep Curls','Plank','Ab Crunch'])assert.equal(ctx.getExerciseRestSeconds(name),60);assert.equal(ctx.getExerciseRestSeconds({name:'Plank',restSeconds:120}),120);assert.equal(ctx.getExerciseRestSeconds({name:'Plank',rest_seconds:75}),75);});
test('countdown uses selected exercise and catches up after background pause',()=>{const {ctx,elements,advance}=setup();ctx.startRestTimer(true,60);assert.equal(elements['rest-timer-display'].textContent,'1:00');advance(15000);assert.equal(elements['rest-timer-display'].textContent,'0:45');advance(45000);assert.equal(elements['rest-timer-display'].textContent,'GO!');ctx.startRestTimer(true,90);assert.equal(elements['rest-timer-display'].textContent,'1:30');ctx.setRestTimerPreset(30);assert.equal(elements['rest-timer-display'].textContent,'0:30');ctx.stopRestTimer();});
const playerSource=fs.readFileSync('js/dashboard/pbb-workout-swipe-player.js','utf8');
test('only completing a new set starts rest, and uses its card duration',()=>{const calls=[];const wrappers=[false,false].map(done=>({classList:{contains:()=>done,toggle:(_,value)=>{done=value;}},querySelector:()=>null}));const card={dataset:{restSeconds:'60'},querySelectorAll:()=>wrappers};const ctx={root:{getWorkoutRestSeconds:()=>60,startRestTimer:(...args)=>calls.push(args)}};vm.createContext(ctx);vm.runInContext(playerSource.slice(playerSource.indexOf('    function toggleSetDone('),playerSource.indexOf('    function ensureFocusCard(')),ctx);ctx.completeNextSet(card);ctx.completeNextSet(card);ctx.completeNextSet(card);assert.deepEqual(calls,[[true,60],[true,60]]);assert.equal(ctx.toggleSetDone(wrappers[0]),false);});
