-- Coach Alerts table: stores AI-generated proactive alerts for the coach
-- These are generated by the scheduled ai-client-monitor function
-- and displayed in the admin dashboard for one-tap action.

-- 1. Create the coach_alerts table
CREATE TABLE IF NOT EXISTS public.coach_alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- Which client this alert is about (NULL for general alerts/ideas)
    client_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    client_name TEXT,

    -- Alert classification
    alert_type TEXT NOT NULL CHECK (alert_type IN (
        'inactive_client',      -- Client hasn't logged in / tracked anything
        'unread_message',       -- Client message waiting for coach reply
        'challenge_dropout',    -- Client falling behind in a challenge
        'streak_broken',        -- Client broke a streak
        'milestone_near',       -- Client close to a milestone (celebrate!)
        'nutrition_gap',        -- Client not hitting macro/calorie goals
        'coaching_idea',        -- AI-generated idea to help a client
        'win_to_celebrate',     -- Client did something great, acknowledge it
        'general_idea'          -- General business/coaching idea
    )),

    -- Priority for sorting
    priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),

    -- Alert content
    title TEXT NOT NULL,              -- Short headline: "Alex hasn't logged in for 3 days"
    description TEXT,                 -- More context about why this matters
    suggested_message TEXT,           -- AI-drafted message ready to send

    -- Action tracking
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'dismissed', 'snoozed')),
    actioned_at TIMESTAMPTZ,          -- When the coach acted on it
    snoozed_until TIMESTAMPTZ,        -- If snoozed, when to resurface

    -- Metadata
    data JSONB DEFAULT '{}'::jsonb    -- Extra context (days_inactive, challenge_name, etc.)
);

-- 2. Indexes for fast querying
CREATE INDEX IF NOT EXISTS idx_coach_alerts_status ON public.coach_alerts(status);
CREATE INDEX IF NOT EXISTS idx_coach_alerts_created ON public.coach_alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_coach_alerts_client ON public.coach_alerts(client_id);
CREATE INDEX IF NOT EXISTS idx_coach_alerts_type ON public.coach_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_coach_alerts_priority ON public.coach_alerts(priority);

-- 3. RLS policies - only admin users can access alerts
ALTER TABLE public.coach_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can view all alerts"
    ON public.coach_alerts FOR SELECT
    USING (
        EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = auth.uid())
    );

CREATE POLICY "Admins can update alerts"
    ON public.coach_alerts FOR UPDATE
    USING (
        EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = auth.uid())
    );

CREATE POLICY "Service role can insert alerts"
    ON public.coach_alerts FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Admins can delete alerts"
    ON public.coach_alerts FOR DELETE
    USING (
        EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = auth.uid())
    );

-- 4. Coach notification preferences table
CREATE TABLE IF NOT EXISTS public.coach_notification_prefs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    coach_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

    -- Notification channels
    whatsapp_enabled BOOLEAN DEFAULT false,
    whatsapp_number TEXT,              -- International format: +61412345678
    push_enabled BOOLEAN DEFAULT true,

    -- Alert frequency
    scan_interval_hours INT DEFAULT 2, -- How often to scan (default every 2 hours)
    quiet_hours_start INT DEFAULT 22,  -- Don't notify after 10pm
    quiet_hours_end INT DEFAULT 7,     -- Don't notify before 7am
    timezone TEXT DEFAULT 'Australia/Brisbane',

    -- Which alert types to receive
    alert_types JSONB DEFAULT '["inactive_client", "unread_message", "challenge_dropout", "streak_broken", "milestone_near", "coaching_idea", "win_to_celebrate"]'::jsonb,

    -- Thresholds
    inactive_days_threshold INT DEFAULT 2,  -- Alert after X days inactive
    unread_hours_threshold INT DEFAULT 4,   -- Alert after X hours unread

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(coach_id)
);

ALTER TABLE public.coach_notification_prefs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage their notification prefs"
    ON public.coach_notification_prefs FOR ALL
    USING (
        EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = auth.uid())
    );
